services:
  backend:
    build: ../backend
    env_file:
      - ./env/.env.local
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: opotrainer_staging
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  redis:
    image: redis:7